### ISSUE TITLE
BadMethodCallException Error (Illuminate)

### ISSUE THREAD

**Issue by maxleistner** [sixmonkey/sloth#26]
Since an update of Illuminate the following error appears: 

```
BadMethodCallException: Method Illuminate\Database\Query\Builder::getTaxonomy does not exist. in /var/www/vendor/illuminate/database/Query/Builder.php:2816
Stack trace:
#0 /var/www/vendor/illuminate/database/Eloquent/Builder.php(1286): Illuminate\Database\Query\Builder->__call()
#1 /var/www/vendor/illuminate/database/Eloquent/Model.php(1570): Illuminate\Database\Eloquent\Builder->__call()
#2 /var/www/vendor/sixmonkey/sloth/src/Plugin/Plugin.php(138): Illuminate\Database\Eloquent\Model->__call()
#3 /var/www/public/cms/wp-includes/class-wp-hook.php(287): Sloth\Plugin\Plugin->loadTaxonomies()
#4 /var/www/public/cms/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#5 /var/www/public/cms/wp-includes/plugin.php(478): WP_Hook->do_action()
#6 /var/www/public/cms/wp-settings.php(540): do_action()
#7 /var/www/public/wp-config.php(13): require_once('/var/www/public...')
#8 /var/www/public/cms/wp-load.php(42): require_once('/var/www/public...')
#9 /var/www/sloth.php(22): include('/var/www/public...')
#10 {main}
(stored in /var/www//logs/exception--2020-04-14--20-37--eafbbf09cf.html)
```

If i'm on php 7.2 i get the error when trying to create a new module via `vagrant ssh` `php sloth.php create-module` if there are custom taxonomies. 

If i'm on php 7.4 the error already loads on page load no matter which page 'm on

![Bildschirmfoto 2020-05-15 um 10 08 57](https://user-images.githubusercontent.com/7567185/87908057-1968e080-ca66-11ea-91e3-e4d1738510b3.png)

**Comment by sixmonkey** [comment]
[fixed](https://github.com/sixmonkey/sloth/commit/b99de7e4d484098f661d891d79e372baf7776e65)

**Comment by maxleistner** [comment]
works fine! Thanks!
